/**
 * Rebuilds the list of models the rewrite picker offers.
 *
 *   pnpm sync:models
 *
 * The Vercel AI Gateway publishes its catalog unauthenticated, and the ComfyUI
 * node builds its own `model` dropdown from that same endpoint. So this script
 * asks the same question the node asks, applies the curation in
 * `rewrite-catalog.ts`, and writes the answer to a committed file.
 *
 * Committed, rather than fetched when the form renders, for two reasons. The
 * form is rendered from the workflow definitions, and those have to hold a
 * model id in the graph itself — a default cannot wait on a network call. And
 * `pnpm check:workflows` has to keep working with nothing but this repo.
 *
 * It also runs before `next build`, so a deploy picks up a provider's point
 * release without anyone re-running it by hand. A build with no network keeps
 * the committed list and says so, rather than failing — being one point release
 * behind is not a reason to refuse to ship.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import {
  curate,
  REWRITE_FAMILIES,
  type CatalogEntry,
  type OfferedModel,
} from "../src/lib/workflows/rewrite-catalog";

const CATALOG_URL = "https://ai-gateway.vercel.sh/v1/models";
const OUTPUT = "src/lib/workflows/generated/gateway-models.ts";

async function fetchCatalog(): Promise<CatalogEntry[]> {
  const response = await fetch(CATALOG_URL, {
    headers: { Accept: "application/json" },
    signal: AbortSignal.timeout(20_000),
  });
  if (!response.ok) {
    throw new Error(`${CATALOG_URL} returned ${response.status}`);
  }
  const body = (await response.json()) as { data?: CatalogEntry[] };
  if (!Array.isArray(body.data) || body.data.length === 0) {
    throw new Error(`${CATALOG_URL} returned no models`);
  }
  return body.data;
}

function render(models: CatalogEntry[]): string {
  const offered = curate(models);

  const list = (offered: OfferedModel[]) =>
    offered
      .map(
        (model) =>
          `  {\n` +
          `    id: ${JSON.stringify(model.id)},\n` +
          `    label: ${JSON.stringify(model.label)},\n` +
          `    vision: ${model.vision},\n` +
          `    free: ${model.free},\n` +
          `    pricePerMillion: ${model.pricePerMillion},\n` +
          `  },`,
      )
      .join("\n");

  return `/**
 * Generated by \`pnpm sync:models\` from ${CATALOG_URL}.
 * Do not edit: run the script. The curation, and why it is these, is in
 * ../rewrite-catalog.ts.
 *
 * Synced ${new Date().toISOString().slice(0, 10)}: ${models.length} models in the catalog,
 * ${REWRITE_FAMILIES.length} families declared, ${offered.length} offered.
 */
import type { OfferedModel } from "../rewrite-catalog";

export const REWRITE_MODELS: OfferedModel[] = [
${list(offered)}
];
`;
}

async function main() {
  let models: CatalogEntry[];
  try {
    models = await fetchCatalog();
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    if (existsSync(OUTPUT)) {
      console.warn(
        `[sync:models] Could not reach the gateway catalog (${reason}). ` +
          `Keeping the committed list in ${OUTPUT}.`,
      );
      return;
    }
    throw new Error(
      `Could not reach the gateway catalog (${reason}), and ${OUTPUT} does not exist yet ` +
        `— there is nothing to fall back to. Run this once with a network connection.`,
    );
  }

  const next = render(models);
  const current = existsSync(OUTPUT) ? readFileSync(OUTPUT, "utf8") : "";
  // The header carries today's date, so compare everything below it: a run
  // that found no new models should leave the file — and the diff — alone.
  const body = (source: string) => source.slice(source.indexOf("import type"));
  if (current && body(current) === body(next)) {
    console.log(`[sync:models] No change. ${OUTPUT} is current.`);
    return;
  }

  writeFileSync(OUTPUT, next);
  console.log(`[sync:models] Wrote ${OUTPUT}.`);
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
